defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:9.4.0-browsers

whitelist: &whitelist
  paths:
    - .eslintignore
    - .eslintrc.json
    - .prettierrc.json
    - .npmignore
    - webpack.config.js
    - README.md
    - package.json
    - yarn.lock
    - build/*
    - src/*
    - stories/*
    - node_modules/*
    - storybook-static/*
    - .storybook/*

version: 2
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/repo
          <<: *whitelist
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Lint code
          command: yarn run lint
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build JavaScript
          command: yarn build
      - persist_to_workspace:
          root: ~/repo
          <<: *whitelist
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Write NPM Token to ~/.npmrc
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Deploy to NPM
          command: npm publish --access=public
  storybook:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build static Storybook Site
          command: yarn run build-storybook
      - run:
          name: Setup Now
          command: yarn global add now
      - run:
          name: Deploy and Alias
          command: cd storybook-static && ~/.yarn/bin/now -t ${NOW_TOKEN} . && ~/.yarn/bin/now -t ${NOW_TOKEN} alias

workflows:
  version: 2
  lint:
    jobs:
      - checkout
      - lint:
          requires:
            - checkout
          filters:
            tags:
              only: /.*/
  storybook:
    jobs:
      - checkout:
          filters:
            tags:
              only: /storybook-[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - storybook:
          requires:
            - checkout
          filters:
            tags:
              only: /storybook-[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
  deploy:
    jobs:
      - checkout:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - build:
          requires:
            - checkout
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
